VITE_BACKEND_URL=


# Feature Flags
VITE_USE_MOCK_DATA=
VITE_ENABLE_DEBUG=
VITE_USE_LIVE_DATA=

VITE_GOOGLE_PLACES_ENABLED=

# google ads...
VITE_ADMOB_APP_ID_ANDROID=
VITE_ADMOB_APP_ID_IOS=

VITE_ADMOB_NATIVE_AD_UNIT_ID_ANDROID=
VITE_ADMOB_NATIVE_AD_UNIT_ID_IOS=

VITE_ADS_NATIVE_TEST_MODE=false
VITE_ADS_ENABLED=true
VITE_ADS_TESTING=true
VITE_ADS_NATIVE_IN_DECK=

VITE_ADS_NATIVE_INTERVAL=2
VITE_ADS_DEBUG=true
